"""Baseline generators — every fine-tune must beat at least the first three.

Why these specific baselines:
- `EmptyGenerator`        — sanity floor. BLEU/ROUGE = 0. Cos-sim is interesting.
- `CopyInputGenerator`    — returns the product name. Tells us if metrics
                            even respond to relevant text.
- `DBAIDescriptionBaseline` — uses the existing `ai_description` field on
                              `products`. This was generated by OpenAI when
                              `iconSuggest.ts` / `fix-dimensions-ai.mjs` ran.
                              It's the "real" baseline to beat.
- `Phi3ZeroShotGenerator` — Phi-3-mini called with a hand-crafted prompt,
                            no fine-tuning. This is what we're trying to
                            improve via QLoRA in Month 2 — beating this
                            with our fine-tune is the headline result.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .dataset import Example, ProductInput, render_input_block, to_chat_messages


# -----------------------------------------------------------------------------
# Trivial baselines — no model required
# -----------------------------------------------------------------------------


@dataclass
class EmptyGenerator:
    name: str = "empty"

    def generate(self, product: ProductInput) -> str:  # noqa: ARG002
        return ""


@dataclass
class CopyInputGenerator:
    """Returns just the product name — checks that BLEU/ROUGE respond to relevant text."""

    name: str = "copy_input"

    def generate(self, product: ProductInput) -> str:
        return product.name


@dataclass
class CopyInputBlockGenerator:
    """Returns the rendered spec block — a fairly hard-to-beat 'free' baseline."""

    name: str = "copy_spec_block"

    def generate(self, product: ProductInput) -> str:
        return render_input_block(product)


# -----------------------------------------------------------------------------
# DB AI description — the "already-shipped" GPT baseline
# -----------------------------------------------------------------------------


@dataclass
class DBAIDescriptionBaseline:
    """Looks up the pre-existing ai_description from the JSONL.

    Use this with `evaluate_examples_with_db_ai(...)` (below) since it depends
    on the per-example data, not just the structured input.
    """

    name: str = "db_ai_description"
    fallback: str = ""
    _by_id: dict[str, str] = field(default_factory=dict)

    def with_examples(self, examples: list[Example]) -> "DBAIDescriptionBaseline":
        self._by_id = {ex.id: (ex.db_ai_description or self.fallback) for ex in examples}
        return self

    def generate(self, product: ProductInput) -> str:  # noqa: ARG002
        # We can't look up by ProductInput because there's no stable id on it,
        # so this generator is meant to be wrapped — see eval_baselines.py.
        raise NotImplementedError("Use generate_for(example) instead.")

    def generate_for(self, example: Example) -> str:
        return self._by_id.get(example.id, self.fallback)


# -----------------------------------------------------------------------------
# Phi-3 zero-shot — the headline baseline that fine-tune must beat
# -----------------------------------------------------------------------------


class Phi3ZeroShotGenerator:
    """Phi-3.5-mini-instruct, 4-bit quantized, called with a chat template.

    First call is slow (loads ~2GB onto GPU). Subsequent calls are ~1–2s on
    a 4080 Laptop. Held in module state so we don't reload across examples.
    """

    name = "phi3_zero_shot"

    def __init__(
        self,
        model_id: str = "microsoft/Phi-3.5-mini-instruct",
        max_new_tokens: int = 220,
        temperature: float = 0.3,
        top_p: float = 0.9,
        load_in_4bit: bool = True,
    ):
        self.model_id = model_id
        self.max_new_tokens = max_new_tokens
        self.temperature = temperature
        self.top_p = top_p
        self.load_in_4bit = load_in_4bit
        self._pipe: Any = None

    def _ensure_loaded(self) -> None:
        if self._pipe is not None:
            return
        # Lazy import — heavy.
        import torch
        from transformers import (  # type: ignore[import-untyped]
            AutoModelForCausalLM,
            AutoTokenizer,
            BitsAndBytesConfig,
            pipeline,
        )

        kwargs: dict[str, Any] = {"device_map": "auto", "torch_dtype": torch.bfloat16}
        if self.load_in_4bit:
            kwargs["quantization_config"] = BitsAndBytesConfig(
                load_in_4bit=True,
                bnb_4bit_compute_dtype=torch.bfloat16,
                bnb_4bit_quant_type="nf4",
                bnb_4bit_use_double_quant=True,
            )

        # NOTE: trust_remote_code=False — the bundled Phi-3 modeling_phi3.py
        # in some HF revisions calls past_key_values.seen_tokens which was
        # removed from modern transformers. The library's own Phi-3 impl is
        # up to date. Tokenizer is fine either way.
        tokenizer = AutoTokenizer.from_pretrained(self.model_id)
        model = AutoModelForCausalLM.from_pretrained(self.model_id, **kwargs)
        self._pipe = pipeline(
            "text-generation",
            model=model,
            tokenizer=tokenizer,
            return_full_text=False,
        )

    def generate(self, product: ProductInput) -> str:
        self._ensure_loaded()
        messages = to_chat_messages(product, target=None)
        out = self._pipe(  # type: ignore[misc]
            messages,
            max_new_tokens=self.max_new_tokens,
            do_sample=self.temperature > 0,
            temperature=self.temperature,
            top_p=self.top_p,
            pad_token_id=self._pipe.tokenizer.eos_token_id,
        )
        return out[0]["generated_text"].strip()


# -----------------------------------------------------------------------------
# Fine-tuned generator — Stage 3 output, evaluated through the same harness
# -----------------------------------------------------------------------------


class FineTunedGenerator:
    """A QLoRA-fine-tuned Phi-3 (or whatever) loaded from a saved adapter.

    Conforms to the same `Generator` protocol as the baselines so eval.py
    can score it identically. The base model is loaded with the same 4-bit
    quantization as during training, then the LoRA adapter is layered on
    top via PEFT.
    """

    def __init__(
        self,
        adapter_path: str,
        base_model_id: str = "microsoft/Phi-3.5-mini-instruct",
        name: str | None = None,
        max_new_tokens: int = 220,
        temperature: float = 0.3,
        top_p: float = 0.9,
        load_in_4bit: bool = True,
    ):
        self.adapter_path = adapter_path
        self.base_model_id = base_model_id
        self.name = name or f"finetuned:{Path(adapter_path).name}"
        self.max_new_tokens = max_new_tokens
        self.temperature = temperature
        self.top_p = top_p
        self.load_in_4bit = load_in_4bit
        self._pipe: Any = None

    def _ensure_loaded(self) -> None:
        if self._pipe is not None:
            return
        import torch
        from peft import PeftModel  # type: ignore[import-untyped]
        from transformers import (  # type: ignore[import-untyped]
            AutoModelForCausalLM,
            AutoTokenizer,
            BitsAndBytesConfig,
            pipeline,
        )

        kwargs: dict[str, Any] = {"device_map": "auto", "torch_dtype": torch.bfloat16}
        if self.load_in_4bit:
            kwargs["quantization_config"] = BitsAndBytesConfig(
                load_in_4bit=True,
                bnb_4bit_compute_dtype=torch.bfloat16,
                bnb_4bit_quant_type="nf4",
                bnb_4bit_use_double_quant=True,
            )
        # Load adapter's tokenizer if it was saved alongside; otherwise base.
        try:
            tokenizer = AutoTokenizer.from_pretrained(self.adapter_path)
        except Exception:
            tokenizer = AutoTokenizer.from_pretrained(self.base_model_id)
        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token

        base = AutoModelForCausalLM.from_pretrained(self.base_model_id, **kwargs)
        model = PeftModel.from_pretrained(base, self.adapter_path)
        # We don't merge — keeps the base cached and the adapter swappable.

        self._pipe = pipeline(
            "text-generation",
            model=model,
            tokenizer=tokenizer,
            return_full_text=False,
        )

    def generate(self, product: ProductInput) -> str:
        self._ensure_loaded()
        messages = to_chat_messages(product, target=None)
        out = self._pipe(  # type: ignore[misc]
            messages,
            max_new_tokens=self.max_new_tokens,
            do_sample=self.temperature > 0,
            temperature=self.temperature,
            top_p=self.top_p,
            pad_token_id=self._pipe.tokenizer.eos_token_id,
        )
        return out[0]["generated_text"].strip()
